### ISSUE TITLE
Set up website as Rails app

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#14]
Based on Slack convo. 1/23 we'll use Solidus (open-source fork of Spree) to build the e-commerce store.  This is a Rails e-commerce solution, so the app should be transitioned over to a Rails app.
- [x] Initial creation: `rails new srvd`
- [x] Set up config.database.yml so Rails can connect to Postgres
- [x] Create database
- [x] Generate any needed ~~models~~, controllers (& actions), and routes
- [x] Move existing index.html landing page to a Rails view

Since this will use Rails asset pipeline, we may have to refactor or eliminate the Gulpfile that is being used for front-end development

**Comment by jjhampton** [comment]
@Scripore I'm going to attempt this myself, may need your assistance/guidance if I run into any stumbling blocks.

**Comment by davidmolina** [comment]
@jjhampton When I get the Heroku credentials, will send over.
