### ISSUE TITLE
Install Solidus gem for Rails e-commerce

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#15]
https://github.com/solidusio/solidus

Example:  http://www.sitepoint.com/fire-up-your-e-commerce-site-with-solidus/

**Comment by Scripore** [comment]
Easy to follow Sitepoint tutorial. Also, here's a video walkthrough that was uploaded just a week ago: https://www.youtube.com/watch?v=0mxGzk1Lfwg
