### ISSUE TITLE
Set up Mailchimp account 

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#16]
We'll be using this for email list management (particularly for the signup form on the landing page, or elsewhere).  Need account info/credentials so someone can log on to Mailchimp and get the embedded form info to insert onto the landing page.

Info on using Mailchimp's embedded forms: 
- http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website
- http://kb.mailchimp.com/lists/signup-forms/host-your-own-signup-forms
- http://www.github.com/rydama/mailchimp-ajax-signup/blob/master/ajax-subscribe.html

**Comment by davidmolina** [comment]
@jjhampton Still pending the credentials. Will send them over when I have them.

**Comment by jjhampton** [comment]
Got the credentials, closing this issue
