### ISSUE TITLE
Identify web hosting solution & deployment strategy

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#2]
Potential needs: 
- SSH access (so developers can log into web host and perform a `git pull` or similar to deploy code from GitHub master branch to the web host's production branch).
  - easyDNS (proposed web host in Dec.) does not offer SSH access currently so this presents a problem if using Git / GitHub for deployment to production
-  Database - web host should provide database for collection of user emails from landing page signup
  - SQL vs noSQL?

**Comment by davidmolina** [comment]
Roger.

**Comment by jjhampton** [comment]
Based on convo in the Slack channel, we may not need SQL database if we go the MailChimp route 100% - we can integrate their form onto our static page that will communicate directly w/ MailChimp.  This negates the need for a back-end language to validate form / save to SQL.

This in turn allows us to use GitHub Pages as a host (since no back-end server needed) - also no need to shop around for a web host that offers SSH so we can use git - we can deploy via a gh-pages branch on GitHub Pages.  

We'd also need to configure CNAME so that GitHub Pages works correctly w/ SRVD's custom domain name: https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by davidmolina** [comment]
I'll work w/ Raf on this. When the site is ready, we'll redirect CNAME.

**Comment by jjhampton** [comment]
Since we're looking at making this a Rails app now (w/ Solidus gem to build our own e-commerce store), Heroku looks like a good option to serve the Rails app.

**Comment by davidmolina** [comment]
@jjhampton Per our Slack conversation, Heroku (hosting), Solidus (e-commerce) and MailChimp (user gathering). We can close this issue when we have those.

**Comment by jjhampton** [comment]
Closing - the above accounts should be set up now.
