### ISSUE TITLE
Add Mailchimp embedded form to landing page for email signup

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#21]
Even though the landing page UI / layout / styling isn't complete yet (issue #10), I'll go ahead and work on adding a Mailchimp embedded form in there.

Info on using Mailchimp's embedded forms:

http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website
http://kb.mailchimp.com/lists/signup-forms/host-your-own-signup-forms
http://www.github.com/rydama/mailchimp-ajax-signup/blob/master/ajax-subscribe.html

**Comment by Scripore** [comment]
All publicly viewable Codepens are MIT licensed. This looks kinda interesting http://codepen.io/Design4/pen/YPJVgd

**Comment by davidmolina** [comment]
Oh, nice!
