### ISSUE TITLE
Identify e-commerce solution to use & set up account

### ISSUE THREAD

**Issue by jjhampton** [OperationCode/srvd#5]
Can be hosted on subdomain such as "store.iserved.co" or similar.

Possible Options:
- BigCommerce
- Shopify
- ~~Shopify embedded app w/ Rails: https://vimeo.com/130247240~~
- Shoppe (Rails, open-source) https://github.com/tryshoppe/shoppe
- Spree (Rails, Open-source); https://github.com/spree/spree

**Comment by davidmolina** [comment]
Shopify embedded app w/ Rails looks straightforward, legit.

**Comment by jjhampton** [comment]
Here are two open-source Rails-based solutions to explore, if we do this as a Rails app: 
https://github.com/tryshoppe/shoppe
https://github.com/spree/spree

**Comment by jjhampton** [comment]
Closing this issue, we'll be using Solidus (open-source fork of Spree), see issue #15
